# ---------- build ----------
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci                 # instala tudo: deps + devDeps
COPY . .
RUN npm run build          # gera ./build JS

# ---------- runtime --------
FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev       # só deps de produção
COPY --from=builder /app/build ./build

ENV NODE_ENV=production
EXPOSE 3333
CMD ["node", "build/server.js"]
    