version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/tasks
      JWT_SECRET: your-super-secret-jwt-key-2024
    ports:
      - "3333:3333"
    command: sh -c "mkdir -p generated/prisma && npx prisma generate && npm run dev"
    volumes:
      - .:/app

volumes:
  db-data:
